name: Build Native Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Native Package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            output-name: CRDTEditor-Windows
            app-folder: CRDTEditor
            archive-cmd: 7z a CRDTEditor-Windows.zip CRDTEditor
          - os: ubuntu-latest
            output-name: CRDTEditor-Linux
            app-folder: CRDTEditor
            archive-cmd: tar -czvf CRDTEditor-Linux.tar.gz CRDTEditor
          - os: macos-latest
            output-name: CRDTEditor-Mac
            app-folder: CRDTEditor.app
            archive-cmd: tar -czvf CRDTEditor-Mac.tar.gz CRDTEditor.app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'liberica'
          cache: 'maven'

    
      - name: Build Fat JAR
        run: mvn clean package

     
      - name: Stage jar for jpackage
        shell: bash
        run: |
          mkdir -p appdir
          cp target/crdt-text-editor-1.0.0.jar appdir/

      - name: Package as app-image
        shell: bash
        run: |
          mkdir -p dist
          jpackage \
            --type app-image \
            --name "CRDTEditor" \
            --input appdir \
            --main-jar crdt-text-editor-1.0.0.jar \
            --main-class Launcher \
            --java-options "--enable-native-access=ALL-UNNAMED" \
            --java-options "-Dglass.gtk.uiScale=1.0" \
            --dest dist

      - name: Archive app
        shell: bash
        working-directory: dist
        run: ${{ matrix.archive-cmd }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output-name }}
          path: |
            dist/*.zip
            dist/*.tar.gz
